name: NodeJS with pnpm and SvelteKit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Use pnpm
      uses: pnpm/action-setup@v2.0.1
      with:
        version: '6.23.6'
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Build Github Pages
      run: pnpx ultra pages
